# Main experiment config file
# Device selection for the experiment
selected_device: "hardware1"  # Choose between 'hardware1' or 'hardware2'
recorder:
  output_dir: "recordings"  # Directory where the recordings will be saved
  duration: 10  # Duration of each recording in seconds
  sample_rate: 48000  # Sample rate in Hz
  channels: 8  # Number of channels for selected hardware
  gain: 1.5  # Gain for the selected hardware
  labels_file: "labels.csv"  # File where labels will be stored

hardware1:
  type: "ReSpeaker"
  device_id: 1  # Device ID for Hardware 1
  channels: 4  # Number of channels for Hardware 1
  gain: 1.0  # Gain for Hardware 1

hardware2:
  type: "MiniDSP"  # Type of Hardware 2
  device_id: 2  # Device ID for Hardware 2
  channels: 8  # Number of channels for Hardware 2
  gain: 1.5  # Gain for Hardware 2

# Experiment metadata and parameters
experiment_meta:
  experiment_id: "exp01"  # Unique experiment identifier
  experiment_type: "category_sound"  # Type of experiment (e.g., "sound")
  run_date: "2024-11-26"  # Date of the experiment
  sample_count: 8  # Number of samples to record
  doa_range: {min: 0, max: 360}  # DOA range in degrees
  elevation_range: {min: -90, max: 90}  # Elevation range in degrees
  frequency_range: {min: 20, max: 2000}  # Frequency range in Hz
  amplitude_range: {min: 0.1, max: 1.0}  # Amplitude range
  categories:  # List of all possible categories for experiments
    - "horn"
    - "noise"
    - "music"
    - "bird"
    - "short_horn"
    - "environmental"  # Additional categories
  selected_categories:  # Categories selected for the current experiment
    - "horn"
  
  doa: 10  # Example: Direction of Arrival for this experiment
  elevation: 0  # Example: Elevation for this experiment

  

